import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        style={{backgroundImage: `url('/BackgroundBlur.png')`, height: "100%", width: "100%"}} 
        className={cn(
          "min-h-screen bg-background font-sans antialiased"
      )}>
        {children}
      </body>
    </html>
  );
}
