import type { Metadata } from "next";
import "../globals.css";

import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        style={{backgroundImage: `url('/BackgroundBlur.png')`, height: "100%", width: "100%", backgroundPosition: "center", backgroundSize: "cover"}} 
        className={cn(
          "bg-background bg-cover font-sans antialiased grid content-center py-full my-8"
        )}>{children}</body>
    </html>
  );
}
